insert into public.store_settings(id,support_email,default_delivery_fee_egp,free_delivery_threshold_egp) values (1,'dentalhub08@outlook.com',75,2500) on conflict(id) do update set support_email=excluded.support_email;

insert into public.categories(name_en,name_ar,slug,sort_order) values
('Dental Instruments','أدوات الأسنان','dental-instruments',1),
('Restorative Materials','مواد الترميم','restorative-materials',2),
('Endodontics','علاج الجذور','endodontics',3),
('Prosthodontics','التركيبات','prosthodontics',4),
('Dental Burs','مبارد الأسنان','dental-burs',5),
('Student Kits','حقائب الطلاب','student-kits',6) on conflict(slug) do nothing;

insert into public.courses(name_en,name_ar,slug,source_code) values
('Operative Dentistry','العلاج التحفظي','operative-dentistry',null),
('Endodontics','علاج الجذور','endodontics','CDD322'),
('Fixed Prosthodontics','التركيبات الثابتة','fixed-prosthodontics','PDD323'),
('Removable Prosthodontics','التركيبات المتحركة','removable-prosthodontics','PDD313') on conflict(slug) do nothing;

insert into public.universities(name_en,name_ar,category,governorate,city) values ('Alamein International University','جامعة العلمين الدولية','national','Matrouh','New Alamein') on conflict do nothing;

insert into public.delivery_rules(rule_type,university_id,fee_egp,priority,is_active) select 'university', id, 50, 100, true from public.universities where name_en='Alamein International University' and not exists(select 1 from public.delivery_rules d where d.rule_type='university' and d.university_id=universities.id);

-- Exact source catalog. Owner requested TOGARY values from the supplied Excel sheet to be used as storefront prices. Blank TOGARY rows remain draft.
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (1,'MIRROR','32',32,'mirror','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (2,'probe','24',24,'probe','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (3,'tweezer','40',40,'tweezer','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (4,'disposable tray','13',13,'disposable-tray','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (5,'cheeck rertractor','13',13,'cheeck-rertractor','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (6,'dental photography mirror',null,null,'dental-photography-mirror','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (7,'four holes high handpiece',null,null,'four-holes-high-handpiece','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (8,'low speed handpiece',null,null,'low-speed-handpiece','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (9,'handpiece oil','130',130,'handpiece-oil','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (10,'245 bur','42',42,'245-bur','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (11,'straight fissure bur','42',42,'straight-fissure-bur','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (12,'round bur','42',42,'round-bur','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (13,'169 bur','42',42,'169-bur','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (14,'bur holder','26.5',26.5,'bur-holder','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (15,'low speed round bur','47',47,'low-speed-round-bur','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (16,'chisel','124(3pcs)',124,'chisel','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (17,'enamel hatchet','24',24,'enamel-hatchet','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (18,'cervical edge trimmer',null,null,'cervical-edge-trimmer','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (19,'spoon excavator','24',24,'spoon-excavator','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (20,'discoid excavator','24',24,'discoid-excavator','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (21,'zinc polycarboxylate cement','79',79,'zinc-polycarboxylate-cement','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (22,'glass ionomer cement',null,null,'glass-ionomer-cement','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (23,'calcium hydroxide',null,null,'calcium-hydroxide','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (24,'MTA','37',37,'mta','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (25,'varnish',null,null,'varnish','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (26,'glass ionomer capsule','78.75',78.75,'glass-ionomer-capsule','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (27,'glass slab',null,null,'glass-slab','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (28,'cement spatula','24',24,'cement-spatula','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (29,'smooth condenser','24',24,'smooth-condenser','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (30,'GIC capsule applicator','892',892,'gic-capsule-applicator','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (31,'calcium hydroxide applicator',null,null,'calcium-hydroxide-applicator','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (32,'MTA applicator','750',750,'mta-applicator','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (33,'microbrush','42',42,'microbrush','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (34,'amalgam capsules',null,null,'amalgam-capsules','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (35,'amalgam carrier','80',80,'amalgam-carrier','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (36,'serrated condenser','24',24,'serrated-condenser','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (37,'egg shaped burnisher','24',24,'egg-shaped-burnisher','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (38,'hollenbeck carver','24',24,'hollenbeck-carver','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (39,'cotton rolls','15.5',15.5,'cotton-rolls','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (40,'tofflemire retainer','75',75,'tofflemire-retainer','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (41,'wedges',null,null,'wedges','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (42,'scissors','40',40,'scissors','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (43,'flame shaped bur','8.5',8.5,'flame-shaped-bur','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (44,'rubber dam kit','950',950,'rubber-dam-kit','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (45,'phosporic acid etching gel','31.5',31.5,'phosporic-acid-etching-gel','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (46,'bonding agent','446',446,'bonding-agent','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (47,'packable composite resin restoration shade A1,A2&A3','210',210,'packable-composite-resin-restoration-shade-a1-a2-a3','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (48,'LIGHT CURE','1420',1420,'light-cure','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (49,'PUTTY index','997',997,'putty-index','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (50,'scalpel','24',24,'scalpel','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (51,'blade','24',24,'blade','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (52,'compsoite brown stain',null,null,'compsoite-brown-stain','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (53,'glycerin gel',null,null,'glycerin-gel','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (54,'celluloid matrices',null,null,'celluloid-matrices','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (55,'2 bioclear matrices',null,null,'2-bioclear-matrices','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (56,'paddle shape plastic filling',null,null,'paddle-shape-plastic-filling','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (57,'PK thomas carver','24',24,'pk-thomas-carver','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (58,'anatomical burnisher','24',24,'anatomical-burnisher','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (59,'composite brush','42',42,'composite-brush','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (60,'stainless steel tray',null,null,'stainless-steel-tray','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (61,'adhesive tip(holding tip)',null,null,'adhesive-tip-holding-tip','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (62,'heavy putty','997',997,'heavy-putty','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (63,'self cure composite resin',null,null,'self-cure-composite-resin','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (64,'depth cutting bur',null,null,'depth-cutting-bur','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (65,'disposable three way air water syringe',null,null,'disposable-three-way-air-water-syringe','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (66,'saliva ejector','105',105,'saliva-ejector','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (67,'cups','12',12,'cups','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (68,'towel holder',null,null,'towel-holder','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (69,'cotton holder','68',68,'cotton-holder','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (70,'cotton roll dispenser',null,null,'cotton-roll-dispenser','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (71,'autoclavable cotton holder','65(2pcs)',65,'autoclavable-cotton-holder','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (72,'topical anesthesia','36',36,'topical-anesthesia','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (73,'anesthesia sygringe',null,null,'anesthesia-sygringe','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (74,'over gloves','7',7,'over-gloves','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (75,'temporary filling material','84',84,'temporary-filling-material','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (76,'light senstive mixing well',null,null,'light-senstive-mixing-well','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (77,'retraction cord',null,null,'retraction-cord','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (78,'hemostatic liquid','68',68,'hemostatic-liquid','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (79,'retraction cord applicator',null,null,'retraction-cord-applicator','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (80,'over shoes',null,null,'over-shoes','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (81,'vinyl polysiloxane',null,null,'vinyl-polysiloxane','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (82,'alginate','150',150,'alginate','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (83,'rubber bowl','15.5',15.5,'rubber-bowl','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (84,'alginate mixing spatula','15.5',15.5,'alginate-mixing-spatula','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (85,'hydro fluoric acid','178',178,'hydro-fluoric-acid','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (86,'silane','210',210,'silane','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (87,'zirconia primer','240',240,'zirconia-primer','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (88,'dual cure resin cement',null,null,'dual-cure-resin-cement','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (89,'oxygen inhibiting gel',null,null,'oxygen-inhibiting-gel','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (90,'bleaching kit','997.5',997.5,'bleaching-kit','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (91,'ivory teeth','10',10,'ivory-teeth','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (92,'sticky wax','10',10,'sticky-wax','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (93,'dispensing gun','470',470,'dispensing-gun','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (94,'die silicon material',null,null,'die-silicon-material','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (95,'rag wheel','37',37,'rag-wheel','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (96,'white acrylic resin','380',380,'white-acrylic-resin','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (97,'gutta percha','99',99,'gutta-percha','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (98,'spreaders','99',99,'spreaders','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (99,'paper point','99',99,'paper-point','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (100,'EDTA','42',42,'edta','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (101,'chlorohexidine','31.5',31.5,'chlorohexidine','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (102,'sodium hypochlorite','31.5',31.5,'sodium-hypochlorite','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (103,'side vented needle','360',360,'side-vented-needle','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (104,'endo file holder','26',26,'endo-file-holder','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (105,'endo ruler','52.5',52.5,'endo-ruler','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (106,'endo files','89',89,'endo-files','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (107,'acrylic bur','52.5',52.5,'acrylic-bur','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (108,'acrylic finishing bur','52',52,'acrylic-finishing-bur','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (109,'diamond finishing disc','36',36,'diamond-finishing-disc','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (110,'wax knife','24',24,'wax-knife','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (111,'carver','24',24,'carver','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (112,'base plate wax','17',17,'base-plate-wax','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (113,'stock tray','13',13,'stock-tray','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (114,'spatula','24',24,'spatula','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (115,'wide blade spatula','26',26,'wide-blade-spatula','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (116,'118 peeso collar plier',null,null,'118-peeso-collar-plier','draft',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (117,'cutting plier','450',450,'cutting-plier','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (118,'ss wire','68',68,'ss-wire','active',true) on conflict(slug) do nothing;
insert into public.products(source_row_no,source_name,source_togary_price_raw,selling_price_egp,slug,status,is_available) values (119,'vaseline',null,null,'vaseline','draft',true) on conflict(slug) do nothing;
