-- University seed derived from the owner-approved master specification.
-- Arabic names remain NULL where not owner-reviewed; Admin can add/edit them.

insert into public.universities(name_en,name_ar,category) values ('Cairo University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Alexandria University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Ain Shams University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Assiut University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Tanta University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Mansoura University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Zagazig University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Capital University / Helwan',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Minya University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Menoufia University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Suez Canal University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Qena / South Valley',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Benha University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Fayoum University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Beni Suef University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Kafr El-Sheikh University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Sohag University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Port Said University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Damanhour University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Damietta University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Aswan University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Suez University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('University of Sadat City',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Arish University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Matrouh University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('New Valley University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Luxor University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Hurghada University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('6th of October University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Misr University for Science and Technology',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('October University for Modern Sciences and Arts (MSA)',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Misr International University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('German University in Cairo',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Modern University for Technology and Information',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Ahram Canadian University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('British University in Egypt',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Sinai University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Future University in Egypt',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Pharos University in Alexandria',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Nahda University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Egyptian Russian University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Delta University for Science and Technology',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Heliopolis University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Deraya University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Badr University in Cairo',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('New Giza University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Horus University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Egyptian Chinese University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Al Salam University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('New Salhia University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Sphinx University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Badr University in Assiut',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Merit University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('May University in Cairo',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Innovation University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Al Riyada University for Science and Technology',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('City University in Cairo',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Al Hayat University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Lotus University in Minya',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Nile Valley University in Fayoum',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Badya University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Obour University for Science and Technology',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Egyptian University in Alamein',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Rashid University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('East Capital University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Memphis University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Misr El Gedida University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Galala University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('King Salman International University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Alamein International University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('New Mansoura University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Alexandria National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Helwan National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Benha National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Mansoura National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Zagazig National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Menoufia National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Minya National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Beni Suef National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('New Ismailia National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Assiut National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('East Port Said National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('South Valley National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Nile National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Egyptian E-Learning University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('French University in Egypt',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Egypt University of Informatics',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Suez National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Tanta National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Damietta National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Damanhour National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Cairo National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Ain Shams National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Sohag National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Kafr El-Sheikh National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('New Valley National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Fayoum National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Luxor National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Sadat City National University',null,null) on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('The American University in Cairo',null,'international') on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Egyptian-Japanese University of Science and Technology',null,'international') on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('German International University',null,'international') on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('ESLSCA University',null,'international') on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Arab Academy for Science, Technology and Maritime Transport',null,'international') on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Arab Open University',null,'international') on conflict(name_en) do nothing;
insert into public.universities(name_en,name_ar,category) values ('Zewail City / University of Science and Technology',null,'international') on conflict(name_en) do nothing;
