-- AIU course supply lists derived from the uploaded source PDFs as captured in the master specification.
do $$
declare aiu uuid; endo uuid; fixedc uuid; rem uuid; op uuid; lid uuid;
begin
select id into aiu from public.universities where name_en='Alamein International University';
select id into endo from public.courses where slug='endodontics';
select id into fixedc from public.courses where slug='fixed-prosthodontics';
select id into rem from public.courses where slug='removable-prosthodontics';
select id into op from public.courses where slug='operative-dentistry';
insert into public.course_supply_lists(university_id,course_id,name,source_code) values (aiu,endo,'Endodontics 2','CDD322') returning id into lid;
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Non-surgical gloves (Nitrile / Latex / Vinyl)','required',1);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Over gloves','required',2);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Mask','required',3);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Eye goggles','required',4);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Grey scrub','required',5);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'White lab coat','required',6);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Wrapping film','required',7);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Disposable towels','required',8);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Disposable tray','required',9);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Surface disinfectant / disinfectant','required',10);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Hand soap','required',11);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Blue wax','required',12);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Torch','required',13);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Wax knife','required',14);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Small sterilization pouches','required',15);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Thin permanent marker (1 mm)','required',16);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Pencil','required',17);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Plastic tray with high sides','required',18);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Cotton pliers','required',19);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Sharp explorer / Endodontic explorer','required',20);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Four-hole high-speed handpiece','required',21);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Round carbide burs or diamond stones — sizes #1, #2, #4, #6','required',22);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Tapered carbide fissure bur','required',23);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Safe-ended tapered diamond stones — different sizes','required',24);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Endo-Z bur','required',25);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Bur holder','required',26);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'K-Files 25 mm — size #8','required',27);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'K-Files 25 mm — size #10','required',28);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'K-Files 25 mm — sizes #15–#40','required',29);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'K-Files 25 mm — sizes #45–#80','required',30);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'H-Files 25 mm — sizes #15–#40','required',31);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'H-Files 25 mm — sizes #45–#80','required',32);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Endobloc / Endodontic ruler','required',33);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'70% ethyl alcohol','required',34);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Gauze swabs','required',35);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Endodontic file holder','required',36);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Luer-lock syringe','required',37);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Side-vented irrigation needle tips','required',38);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'5.25% sodium hypochlorite','required',39);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Plastic cups','required',40);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'EDTA paste or gel','required',41);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'17% EDTA solution','required',42);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'2% chlorhexidine','required',43);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Standardized gutta-percha points — sizes #15–#40','required',44);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Standardized gutta-percha points — sizes #45–#80','required',45);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Absorbent paper points — sizes #15–#40','required',46);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Absorbent paper points — sizes #45–#80','required',47);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Eugenol-based sealer','required',48);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Cement spatula','required',49);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Paper pads','required',50);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Sharp scissors','required',51);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Finger spreaders','required',52);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Hand plugger','required',53);
insert into public.course_supply_lists(university_id,course_id,name,source_code) values (aiu,fixedc,'Fixed Prosthodontics 3','PDD323') returning id into lid;
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Towel','required',1);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Surface disinfectant spray','required',2);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Diagnostic set — Mirror, Probe and Tweezer','required',3);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Model with full set of typodont teeth — Maxillary + Mandibular','required',4);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'High-speed handpiece','required',5);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Tapered round-end diamond stone #10, #11, #12, #13 — green or blue grit','required',6);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Tapered round-end diamond finishing stone #11, #12, #13 — red or yellow grit','required',7);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Tapered flat-end diamond stone #12, #13 — green or blue grit','required',8);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Straight handpiece + low-speed turbine','required',9);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Diamond finishing disc for acrylic resin','required',10);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Acrylic bur','required',11);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Acrylic finishing stones','required',12);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Rag wheel','required',13);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Bur holder','required',14);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Putty impression material','required',15);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Light-body impression material','required',16);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Stainless-steel trays — different sizes','required',17);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Impression mixing spatula','required',18);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Glass slab','required',19);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Scalpel handle','required',20);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Blade #11','required',21);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'White acrylic resin (powder/monomer) OR bis-acrylic temporary crown material','alternative',22);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Glass Dappen dish','required',23);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Dental carver','required',24);
insert into public.course_supply_lists(university_id,course_id,name,source_code) values (aiu,rem,'Removable Prosthodontics III','PDD313') returning id into lid;
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Wax knife','required',1);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Carver','required',2);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Rubber bowl','required',3);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Scissors & cutter','required',4);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Spatula','required',5);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Two glass slabs','required',6);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Alginate','required',7);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Green self-cure acrylic','required',8);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Small glass cup','required',9);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Stock trays — Partial No. 2 and No. 3','required',10);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Clay','required',11);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Base plate wax','required',12);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Wide-blade spatula','required',13);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Torch','required',14);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Gas lighter refill','required',15);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Acrylic bur','required',16);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Vaseline','required',17);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'118 Peeso collar pliers','required',18);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Cutting pliers','required',19);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Colored pencils — red, blue, brown, black','required',20);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Low-speed handpiece','required',21);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Tapered round bur — size 13 (for low-speed handpiece)','required',22);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Inverted cone bur — diameter 2 (for low-speed handpiece)','required',23);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Round bur — diameter 1.5 (for low-speed handpiece)','required',24);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Ivory teeth — upper/lower first molar, upper/lower premolars, maxillary canines','required',25);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Dental stainless-steel wire — size 0.7, 2–3 meters','required',26);
insert into public.course_supply_lists(university_id,course_id,name,source_code) values (aiu,op,'Operative Dentistry',null) returning id into lid;
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Rubber dam sheets — medium','required',1);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Rubber dam template (R.D template)','required',2);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Winged and wingless rubber dam clamps — anterior, premolar, molar','required',3);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Rubber dam clamp forceps','required',4);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Rubber dam punch','required',5);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Rubber dam metal frame','required',6);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Glycerin','required',7);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Brush','required',8);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Dental floss','required',9);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Elastic wedges','required',10);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Teflon','required',11);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Liquid dam (Liquidam)','required',12);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'37% phosphoric acid etching gel','required',13);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Bonding agent','required',14);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Microbrush','required',15);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Packable composite resin restoration — shades A1, A2, A3 (Composite Kit)','required',16);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Composite compules — E1, D1, D3','required',17);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Compule gun','required',18);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Flowable composite resin restoration — shade A3','required',19);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Light curing device — control modes/time; caries-detector mode optional','optional',20);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Heavy putty and light-body impression material','required',21);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Scalpel + blade','required',22);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Composite stain — brown/white/blue (optional)','optional',23);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Glycerin gel','required',24);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Celluloid strips','required',25);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Bioclear matrices for anterior','required',26);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Sectional matrices — different sizes + V-shape ring + diamond wedges','required',27);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Saddle matrix','required',28);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'360° matrix','required',29);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Paddle-shape plastic filling instrument / composite application kit','required',30);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Small ball burnisher','required',31);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Composite condenser','required',32);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'PK Thomas carver','required',33);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Anatomical burnisher','required',34);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Fork-type tight contact tool','required',35);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Composite modeling brush (hair or silicon) + modeling resin (optional)','optional',36);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Flame-shape finishing bur / composite finishing burs kit','required',37);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'TR 11, 12, 13 finishing burs','required',38);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Finishing discs kit','required',39);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Finishing strips','required',40);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Polishing burs kit — rubber cups / wheels / points','required',41);
insert into public.course_supply_items(list_id,source_item_name,requirement_level,sort_order) values (lid,'Polishing paste','required',42);
end $$;
